import {sphereAttitude} from './attitude.js';
import * as THREE from './vendor/three.module.js';
import {worldPosition,densify,clipSegment,clipPolygon,validateState,distance,bearing} from './geo.js';
const $=id=>document.getElementById(id),svgNS='http://www.w3.org/2000/svg';
const el=(tag,text,cls)=>{let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
let hatchSerial=0;
function hatch(svg,color){
 const id='railview-hatch-'+(++hatchSerial),defs=document.createElementNS(svgNS,'defs'),pattern=document.createElementNS(svgNS,'pattern');
 for(const [k,v] of Object.entries({id,width:9,height:9,patternUnits:'userSpaceOnUse',patternTransform:'rotate(35)'}))pattern.setAttribute(k,v);
 const bg=document.createElementNS(svgNS,'rect');for(const [k,v] of Object.entries({width:9,height:9,fill:color,'fill-opacity':.07}))bg.setAttribute(k,v);
 const line=document.createElementNS(svgNS,'path');for(const [k,v] of Object.entries({d:'M0 0V9',stroke:color,'stroke-width':1.4,'stroke-opacity':.32}))line.setAttribute(k,v);
 pattern.append(bg,line);defs.append(pattern);svg.prepend(defs);return 'url(#'+id+')';
}
export function setupProject(view){
 let state={version:0,layers:[],calibrations:{}},dirty=false,revision=0,ready=false,saving=false,show=true,paths=[],mapLayers=[],groundMeshes=[],neighbors=[],lastView='',toastTimer,replacing=null,range=1500;
 const toast=msg=>{clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,7000)};
 function calibration(){const s=view.station();return state.calibrations[s.id]||{yaw:0,pitch:0,ground:s.alt-s.heightAboveTakeoff}}
 function selected(){const fit=view.station().geometry?.headingCalibration;$('headingStatus').textContent=fit?'Rumbo contrastado con fotos y GPS':'Rumbo por verificar';$('featureInfo').hidden=true;buildOverlay();buildNeighbors()}
 function showInfo(feature,layer){const box=$('featureInfo');box.replaceChildren();const close=el('button','×','close-dialog');close.setAttribute('aria-label','Cerrar información');close.onclick=()=>box.hidden=true;box.append(close,el('h3',feature.name),el('p',layer.name,'muted'));if(feature.folder)box.append(el('p',feature.folder));if(feature.description)box.append(el('p',feature.description));for(const [k,v] of Object.entries(feature.properties||{})){const p=el('p');p.append(el('b',k+': '),document.createTextNode(String(v)));box.append(p)}box.append(el('p',`Geometría: ${feature.type} · Altura: ${feature.altitudeMode}`,'muted'));box.hidden=false}
 function makeMap(){for(const l of mapLayers)view.map.removeLayer(l);view.map.getContainer().querySelectorAll('pattern[id^="railview-hatch-"]').forEach(p=>p.parentNode.remove());mapLayers=[];if(!show)return;for(const layer of state.layers.filter(l=>l.visible)){for(const f of layer.features){let m;const options={color:layer.color,opacity:layer.opacity,weight:3,fillOpacity:.12};const ll=c=>[c[1],c[0]];
 if(f.type==='Point')m=L.circleMarker(ll(f.coordinates),{...options,radius:6,fillOpacity:.9});else if(f.type==='LineString')m=L.polyline(f.coordinates.map(ll),options);else if(f.type==='Polygon')m=L.polygon(f.coordinates.map(r=>r.map(ll)),options);else m=L.polygon(f.coordinates.map(ll),{...options,fillOpacity:.18});m.addTo(view.map).on('click',()=>showInfo(f,layer));if(f.type==='Polygon'){const path=m.getElement();if(path){const fill=hatch(path.ownerSVGElement,layer.color);path.setAttribute('fill',fill);path.setAttribute('fill-opacity',layer.opacity)}}const label=el('span',f.name);m.bindTooltip(label);mapLayers.push(m)}}}
 function disposeMeshes(){for(const m of groundMeshes){view.scene.remove(m);m.geometry.dispose();m.material.map?.dispose();m.material.dispose()}groundMeshes=[]}
 function buildOverlay(){paths=[];$('overlay').replaceChildren();disposeMeshes();lastView='';if(!view.station()||!show)return;const s=view.station(),c=calibration();for(const layer of state.layers.filter(l=>l.visible)){const fillPaint=hatch($('overlay'),layer.color);for(const f of layer.features){const point=world=>new THREE.Vector3(...worldPosition(world,s,f.altitudeMode,c.ground));
 if(f.type==='GroundOverlay'){const vs=f.coordinates.map(point);if(vs.every(v=>v.length()>range))continue;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vs.flatMap(v=>v.toArray()),3));g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,1,1,0,1],2));g.setIndex([0,1,2,0,2,3]);const tex=new THREE.TextureLoader().load(f.image);tex.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide,transparent:true,opacity:layer.opacity,depthWrite:false});const mesh=new THREE.Mesh(g,material);mesh.renderOrder=2;view.scene.add(mesh);groundMeshes.push(mesh)}
 const rings=f.type==='Point'?[[f.coordinates]]:f.type==='Polygon'?f.coordinates:[f.coordinates];let vectors=rings.map(r=>(f.type==='Point'?r:densify(r)).map(point));if(f.type==='GroundOverlay')vectors=vectors.map(v=>[...v,v[0]]);if(vectors.every(v=>v.every(p=>p.length()>range)))continue;
 let fillNode;if(f.type==='Polygon'){fillNode=document.createElementNS(svgNS,'path');fillNode.setAttribute('fill',fillPaint);fillNode.setAttribute('fill-rule','evenodd');fillNode.setAttribute('opacity',layer.opacity);fillNode.style.pointerEvents='none';$('overlay').append(fillNode)}
 const node=document.createElementNS(svgNS,f.type==='Point'?'circle':'path');node.setAttribute('stroke',layer.color);node.setAttribute('stroke-width',f.type==='Point'?'2':'3');node.setAttribute('opacity',layer.opacity);node.setAttribute('fill',f.type==='Point'?layer.color:'none');if(f.type==='Point')node.setAttribute('r','6');node.setAttribute('stroke-linecap','round');node.setAttribute('tabindex','0');node.setAttribute('role','button');node.setAttribute('aria-label',f.name);const title=document.createElementNS(svgNS,'title');title.textContent=f.name;node.append(title);node.onclick=()=>showInfo(f,layer);node.onkeydown=e=>{if(e.key==='Enter')showInfo(f,layer)};$('overlay').append(node);paths.push({node,fillNode,vectors,point:f.type==='Point'})}}
 const legend=$('layerLegend');legend.replaceChildren();const active=state.layers.filter(l=>l.visible);if(!active.length){legend.append(el('span',state.layers.length?'Capas ocultas':'Sin capas KMZ','legend-empty'))}else for(const l of active){const chip=el('button',`${l.name} · ${l.features.length}`);chip.style.borderLeft=`3px solid ${l.color}`;legend.append(chip)}}
 function buildNeighbors(){neighbors=[];lastView='';$('hotspots').replaceChildren();const s=view.station(),current=view.stations.indexOf(s);[current-1,current+1].filter(i=>i>=0&&i<view.stations.length).map(i=>({v:view.stations[i],i,d:distance(s,view.stations[i])})).filter(n=>n.d>3&&n.d<2500).forEach(n=>{const btn=el('button',undefined,'hotspot');const forward=n.i>current;btn.append(el('span','', 'ground-chevron'),el('small',`${forward?'Avanzar':'Volver'} · ${Math.round(n.d)} m`));btn.setAttribute('aria-label',`${forward?'Avanzar':'Volver'} ${Math.round(n.d)} m hacia ${n.v.name}`);btn.onclick=()=>view.select(n.i);btn.title=`${n.v.name} · Posición sobre suelo aproximado`;const ground=state.calibrations[n.v.id]?.ground??(n.v.alt-n.v.heightAboveTakeoff);const vec=new THREE.Vector3(...worldPosition([n.v.lon,n.v.lat,ground],s,'absolute',0));neighbors.push({btn,vec});$('hotspots').append(btn)})}
 function frame(){if(!view.station())return;const c=calibration();view.sphere.quaternion.copy(sphereAttitude(view.station().geometry,c));const size=view.size(),camera=view.camera;const key=[camera.quaternion.toArray().join(','),camera.fov,size.width,size.height,show,paths.length].join('|');if(key===lastView)return;lastView=key;camera.updateMatrixWorld();const tanY=Math.tan(camera.fov*Math.PI/360),tanX=tanY*camera.aspect;const toCamera=v=>v.clone().applyMatrix4(camera.matrixWorldInverse).toArray();const project=p=>[(p[0]/(-p[2]*tanX)+1)*size.width/2,(1-p[1]/(-p[2]*tanY))*size.height/2];
 for(const p of paths){if(p.point){const a=toCamera(p.vectors[0][0]);const visible=a[2]<-.2&&p.vectors[0][0].length()<=range;p.node.style.display=visible?'':'none';if(visible){let xy=project(a);p.node.setAttribute('cx',xy[0]);p.node.setAttribute('cy',xy[1])}}else{if(p.fillNode){const fill=p.vectors.map(r=>clipPolygon(r.map(toCamera),tanX,tanY)).filter(r=>r.length>=3).map(r=>r.map((v,i)=>{const xy=project(v);return (i?'L':'M')+xy[0].toFixed(1)+','+xy[1].toFixed(1)}).join('')+'Z').join('');p.fillNode.setAttribute('d',fill)}let d='';for(const ring of p.vectors){for(let i=1;i<ring.length;i++){if(ring[i-1].length()>range&&ring[i].length()>range)continue;const seg=clipSegment(toCamera(ring[i-1]),toCamera(ring[i]),tanX,tanY);if(!seg)continue;const a=project(seg[0]),b=project(seg[1]);d+=`M${a[0].toFixed(1)},${a[1].toFixed(1)}L${b[0].toFixed(1)},${b[1].toFixed(1)}`}}p.node.setAttribute('d',d)}}for(const n of neighbors){const a=toCamera(n.vec),xy=a[2]<-.2?project(a):[-1000,-1000];n.btn.hidden=a[2]>=-.2||xy[0]<30||xy[0]>size.width-30||xy[1]<100||xy[1]>size.height-120;if(!n.btn.hidden){n.btn.style.left=xy[0]+'px';n.btn.style.top=xy[1]+'px'}}}
 const load=async()=>{try{const r=await fetch('./state.json');if(!r.ok)throw Error('No se pudieron cargar las capas');state=validateState(await r.json());ready=true;makeMap();selected()}catch(e){toast(e.message)}};load();
 if(document.modelContext?.registerTool){const controller=new AbortController();for(const tool of [{name:'list_railview_stations',description:'Consulta las panorámicas georreferenciadas disponibles.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({stations:view.stations.map(s=>({id:s.id,name:s.name,lat:s.lat,lon:s.lon,partial:s.partial}))})},{name:'navigate_railview_station',description:'Navega el visor a una panorámica existente, sin modificar el proyecto.',inputSchema:{type:'object',properties:{stationId:{type:'string'}},required:['stationId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const i=view.stations.findIndex(s=>s.id===input.stationId);if(i<0)throw Error('Panorámica no encontrada');await view.select(i);return{stationId:view.station().id}}},{name:'inspect_railview_layers',description:'Consulta las capas cargadas, su visibilidad y los cambios pendientes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({layers:state.layers.map(l=>({id:l.id,name:l.name,visible:l.visible,features:l.features.length})),unsavedChanges:dirty})}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
 return{selected,frame,toast};
}
